/// Flutter icons Tower
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tower
///      fonts:
///       - asset: fonts/Tower.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Tower {
  Tower._();

  static const _kFontFam = 'Tower';
  static const _kFontPkg = null;

  static const IconData radio_tower = IconData(0xf393, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadcast_tower = IconData(0xf519, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
